// AUTO-GENERATED from Papierkram Swagger spec (GET /api/v1/api-docs .../expense/vouchers category enum).
// Exact German account labels the API accepts for expense-voucher line items. Do not edit by hand.
export const EXPENSE_CATEGORIES = [
  "Andere Anlagen",
  "Betriebsausstattung (Anlage)",
  "Büroeinrichtung",
  "Fahrzeuge (PKW)",
  "Geschäftsausstattung",
  "Grundstücke",
  "GWG ab 2018: 250 bis 1000 EUR (Sammelposten)",
  "GWG ab 2018: bis 800 EUR (Geringwertiges Wirtschaftsgut)",
  "GWG vor 2018: 150 bis 1000 EUR (Sammelposten)",
  "GWG vor 2018: bis 410 EUR (Geringwertiges Wirtschaftsgut)",
  "Sofortabschreibung ab 2021: PC, Laptop und andere Computer-Hardware",
  "Software (Anlage)",
  "Technische Anlagen und Maschinen",
  "Aufwendungen für ein häusliches Arbeitszimmer",
  "Ausgangsfrachten",
  "Betriebsbedarf",
  "Bewirtungskosten",
  "Bezugsnebenkosten",
  "Buchführungskosten",
  "Büroartikel",
  "Bürobedarf",
  "Fahrten zwischen Wohnung und Betriebsstätte und Familienheimfahrten (abziehbarer Anteil)",
  "Fahrten zwischen Wohnung und Betriebsstätte und Familienheimfahrten (nicht abziehbarer Anteil)",
  "Fahrtkostenerstatt. Whg./Arbeitsstätte",
  "Fortbildung",
  "Fremdleistung (Dienstleistung)",
  "Garagenmieten",
  "Gas, Strom, Wasser",
  "Gehälter",
  "Geschäftsessen",
  "Gesetzliche Sozialaufwendungen",
  "Gewerbesteuer",
  "Gewerbesteuer Nachzahlung oder Erstattung",
  "Grundsteuer",
  "Heizung",
  "Kfz-Reparaturen",
  "Kfz-Steuern",
  "Kfz-Versicherungen",
  "Körperschaftsteuer",
  "Laufende Kfz-Betriebskosten",
  "Leasing",
  "Leergut",
  "Löhne",
  "Miete",
  "Mietleasing bewegliche Wirtschaftsgüter für technische Anlagen und Maschinen",
  "Nebenkosten des Geldverkehrs",
  "Nicht abzugsfähige Bewirtungskosten",
  "Porto",
  "Rechts- und Beratungskosten",
  "Reinigung",
  "Reisekosten Arbeitnehmer",
  "Reisekosten Arbeitnehmer Fahrtkosten",
  "Reisekosten Arbeitnehmer Verpflegungsmehraufwand",
  "Reisekosten Arbeitnehmer Übernachtungsaufwand",
  "Reisekosten UN Verpfleg.mehraufwand",
  "Reisekosten UN Übernachtungsaufwand",
  "Reisekosten Unternehmer",
  "Reisekosten Unternehmer Fahrtkosten",
  "Reparatur/Instandh. Betriebs- u. Gesch.",
  "Repräsentationskosten",
  "Roh-, Hilfs- und Betriebsstoffe",
  "Software/EDV (Büroartikel)",
  "Sonstige betriebliche Aufwendungen",
  "Sonstige Kfz-Kosten",
  "Spesen (Reisekosten Unternehmer)",
  "Telefon",
  "Verkaufsprovisionen",
  "Versicherungen",
  "Wareneingang",
  "Werbekosten",
  "Zeitschriften, Bücher",
  "Zinsabschlagsteuer",
  "Zinsen und ähnliche Aufwendungen",
  "Zuwendungen,Spenden steuerl. n. abziehb.",
  "Erlöse Leergut",
  "Private KFZ Nutzung (1% Regel)",
  "Private Verwendung von Gegenständen",
  "Privatentnahme Waren/Gegenstände",
  "Provisionserlöse",
  "Sonstige Einnahme (Erlöse)",
  "Zinsen und ähnliche Erträge",
  "Zuschüsse",
  "Geldtransit (Einzahlung)",
  "Privateinlagen",
  "Geldtransit (Auszahlung)",
  "Privatentnahmen allgemein",
  "Umsatzsteuer Erstattung (nur EÜR)",
  "Umsatzsteuer frühere Jahre",
  "Umsatzsteuer Vorjahr",
  "Umsatzsteuervorauszahlungen",
  "Umsatzsteuervorauszahlungen 1/11",
  "Umsatzsteuer Erstattung",
  "Umsatzsteuer Erstattung frühere Jahre",
  "Umsatzsteuervorauszahlung Guthaben",
] as const;
